// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bd-U6eCMae9axHwZEFjzdit4BtxtwJM',
    appId: '1:796571754442:ios:5d6c060b18da8fb8e23933',
    messagingSenderId: '796571754442',
    projectId: 'flutter-todo-f3ecc',
    storageBucket: 'flutter-todo-f3ecc.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0bd-U6eCMae9axHwZEFjzdit4BtxtwJM',
    appId: '1:796571754442:ios:5d6c060b18da8fb8e23933',
    messagingSenderId: '796571754442',
    projectId: 'flutter-todo-f3ecc',
    storageBucket: 'flutter-todo-f3ecc.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQH9_tJm-_ES7MaiGsIN9lippxnuYp_6g',
    appId: '1:796571754442:web:f0bdcb45f4a70cdbe23933',
    messagingSenderId: '796571754442',
    projectId: 'flutter-todo-f3ecc',
    authDomain: 'flutter-todo-f3ecc.firebaseapp.com',
    storageBucket: 'flutter-todo-f3ecc.firebasestorage.app',
    measurementId: 'G-SKLT7NSZ3Z',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQH9_tJm-_ES7MaiGsIN9lippxnuYp_6g',
    appId: '1:796571754442:web:3b76d260f09196a9e23933',
    messagingSenderId: '796571754442',
    projectId: 'flutter-todo-f3ecc',
    authDomain: 'flutter-todo-f3ecc.firebaseapp.com',
    storageBucket: 'flutter-todo-f3ecc.firebasestorage.app',
    measurementId: 'G-JHFKPYQ09P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQKcs2F7a1tXaWhxH-3NQn0IqiWq3ll0',
    appId: '1:796571754442:android:e4ca1c0ef49f2d39e23933',
    messagingSenderId: '796571754442',
    projectId: 'flutter-todo-f3ecc',
    storageBucket: 'flutter-todo-f3ecc.firebasestorage.app',
  );

}